options ls=80 ps =50 nodate;
data artdat;
    infile "/folders/myfolders/assignment 11/artdat.txt" firstobs=2;
    input trt block y;
proc print data=artdat;
proc glm data=artdat;
    class trt block;
    model y=trt block;
data twoway;
    infile "/folders/myfolders/assignment 11/twoway.txt" firstobs=2;
    input x1 x2 x3 x4 x5 y;
proc print data=twoway;
proc glm data=twoway;
    class x1 x2 x3 x4 x5;
    model y = x1 x2 x3 x4 x5;
proc glm data=twoway;
    class x3 x4 x5 x1 x2;
    model y = x3 x4 x5 x1 x2;
data new1;
    set twoway;
    if x1=0 and x2=0 and x4=1 then delete;
proc print data=new1;
proc glm data=new1;
    class x1 x2 x3 x4 x5;
    model y= x1 x2 x3 x4 x5;
proc glm data=new1;
    class x3 x4 x5 x1 x2;
    model y= x3 x4 x5 x1 x2;
data new2;
    set artdat;
    if trt=3 and block=2 then delete;
proc glm data=new2;
    class trt block;
    model y=trt block;
    
run;